"""Expense-report PDF generator (reportlab).

Mirrors the document skeleton used by ``splitsheet/pdf_generator.py`` — same
brand color and ``SimpleDocTemplate`` + ``Table``/``TableStyle`` approach.
"""

import io

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from expenses.common import category_label, category_totals, fmt_money, grand_total, sorted_rows

BRAND = colors.HexColor("#1a3a2a")


def generate_expense_report_pdf(
    rows: list[dict],
    scope_label: str,
    category_label_str: str,
    generated_on: str,
) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        leftMargin=0.6 * inch,
        rightMargin=0.6 * inch,
    )

    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle(
        "ExpenseReportTitle",
        parent=styles["Title"],
        fontSize=24,
        spaceAfter=4,
        textColor=BRAND,
        alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        "ExpenseReportSubtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#555555"),
        alignment=TA_CENTER,
        spaceAfter=2,
    )
    section_heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=BRAND,
        spaceBefore=16,
        spaceAfter=6,
    )
    cell_style = ParagraphStyle(
        "Cell",
        parent=styles["Normal"],
        fontSize=8.5,
        leading=11,
    )
    cell_right_style = ParagraphStyle(
        "CellRight",
        parent=cell_style,
        alignment=2,  # right
    )

    total = grand_total(rows)

    # --- Header ---
    elements.append(Paragraph("Expense Report", title_style))
    elements.append(Paragraph(scope_label, subtitle_style))
    elements.append(Paragraph(f"Category: {category_label_str}", subtitle_style))
    elements.append(Paragraph(f"Generated {generated_on}", subtitle_style))
    elements.append(Spacer(1, 10))
    elements.append(HRFlowable(width="100%", thickness=2, color=BRAND, spaceAfter=14))

    # --- Totals ---
    elements.append(
        Paragraph(
            f"<b>Total tracked expenses: {fmt_money(total)}</b> "
            f"&nbsp;&nbsp;·&nbsp;&nbsp; {len(rows)} expense{'' if len(rows) == 1 else 's'}",
            ParagraphStyle("Totals", parent=styles["Normal"], fontSize=12, textColor=BRAND),
        )
    )

    # --- By category ---
    cat_rows = category_totals(rows)
    if cat_rows:
        elements.append(Paragraph("By category", section_heading_style))
        cat_data = [["Category", "Total"]]
        for cat, amount in cat_rows:
            cat_data.append([category_label(cat), fmt_money(amount)])
        cat_table = Table(cat_data, colWidths=[4.0 * inch, 3.3 * inch])
        cat_table.setStyle(_table_style())
        elements.append(cat_table)

    # --- Itemized ---
    elements.append(Paragraph("Expenses", section_heading_style))
    header = ["Date", "Project", "Artist", "Description", "Category", "Amount"]
    item_data = [[Paragraph(f"<b>{h}</b>", cell_style if h != "Amount" else cell_right_style) for h in header]]
    for r in sorted_rows(rows):
        item_data.append(
            [
                Paragraph(r.get("incurred_on") or "—", cell_style),
                Paragraph(r.get("project_name") or "—", cell_style),
                Paragraph(r.get("artist_name") or "—", cell_style),
                Paragraph(r.get("description") or "—", cell_style),
                Paragraph(category_label(r.get("category")), cell_style),
                Paragraph(fmt_money(r.get("amount")), cell_right_style),
            ]
        )
    # TOTAL row
    item_data.append(
        [
            Paragraph("", cell_style),
            Paragraph("", cell_style),
            Paragraph("", cell_style),
            Paragraph("", cell_style),
            Paragraph("<b>TOTAL</b>", cell_style),
            Paragraph(f"<b>{fmt_money(total)}</b>", cell_right_style),
        ]
    )
    col_widths = [0.85 * inch, 1.35 * inch, 1.15 * inch, 2.05 * inch, 0.95 * inch, 0.95 * inch]
    item_table = Table(item_data, colWidths=col_widths, repeatRows=1)
    item_table.setStyle(_table_style(total_row=True))
    elements.append(item_table)

    elements.append(Spacer(1, 16))
    elements.append(
        Paragraph(
            "Generated by Msanii. Amounts in USD.",
            ParagraphStyle(
                "Footer",
                parent=styles["Normal"],
                fontSize=8,
                textColor=colors.HexColor("#aaaaaa"),
                alignment=TA_CENTER,
                spaceBefore=8,
            ),
        )
    )

    doc.build(elements)
    buffer.seek(0)
    return buffer


def _table_style(total_row: bool = False) -> TableStyle:
    cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), BRAND),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (-1, 0), (-1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#999999")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
    ]
    if total_row:
        cmds.append(("LINEABOVE", (0, -1), (-1, -1), 1, colors.black))
        cmds.append(("BACKGROUND", (0, -1), (-1, -1), colors.white))
    return TableStyle(cmds)
